<a href="https://colab.research.google.com/github/kimsooyoung/iap_hanyang/blob/main/IDAI_Linear_Regression_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

º 랜덤한 값을 가지는 텐서 생성

1. `torch.rand()` : 0과 1 사이의 숫자를 균등하게 생성
2. `torch.rand_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
3. `torch.randn()` : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성
4. `torch.randn_like()` :  사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
5. `torch.randint()` : 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32
6. `torch.randint_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
7. `torch.randperm()` : 주어진 범위 내의 정수를 랜덤하게 생성

In [3]:
torch.empty(5, 3)

tensor([[8.2319e-36, 0.0000e+00, 2.3694e-38],
        [9.2196e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
torch.rand(5, 3)

tensor([[0.8774, 0.3740, 0.4055],
        [0.7391, 0.9450, 0.2407],
        [0.4003, 0.7967, 0.4453],
        [0.6464, 0.2645, 0.1754],
        [0.2309, 0.6678, 0.4656]])

In [5]:
torch.randn(5, 3)

tensor([[-0.1132, -0.4833,  0.0719],
        [ 0.5638, -0.2346,  0.6653],
        [-1.7273,  1.9043, -1.0549],
        [-0.8937, -0.7524,  2.1464],
        [-0.5911, -1.7775,  0.9386]])

In [7]:
x = torch.rand(1)
print(x, x.item())

tensor([0.2883]) 0.288310170173645


In [9]:
import numpy as np

a = torch.ones(5)
b = a.numpy()
c = np.ones(5)
d = torch.from_numpy(c)

print(b) # tensor
print(a) # numpy
print(c) # numpy
print(d) # tensor 

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## Using GPU

In [12]:
x = torch.tensor((5, 3))
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y

print(z, z.to('cpu'), torch.double)

tensor([6, 4], device='cuda:0') tensor([6, 4]) torch.float64


## Cost Function - MSE

<img width="300" alt="image" src="https://user-images.githubusercontent.com/12381733/167244192-5974984d-a3eb-4682-833f-a4f9c6d41670.png">

```
torch.nn.MSELoss(size_average=None, reduce=None, reduction='mean')

import torch.nn as nn.criterion = nn.CrossEntropyLoss()
...
loss = criterion(input, target)
```

<img width="379" alt="image" src="https://user-images.githubusercontent.com/12381733/167244134-18d4ba34-ebd0-4a27-8058-34b684cabad2.png">

```
import torch
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)
```

## Example: Linear Regression 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/12381733/167244269-87d178ab-90bd-4543-9164-df09c656ae39.png">

In [16]:
import torch
import torch.optim as optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[5], [6], [7]])


W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr = 0.01)
epochs = 3000
for epoch in range(epochs):
    H = x_train * W + b
    cost = torch.mean((H - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if (epoch+1) % 300 == 0:
            print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
                    (epoch+1), epochs, W.item(), b.item(), cost.item()
            ))

Epoch  300/3000 W: 1.637, b: 2.551 Cost: 0.302633
Epoch  600/3000 W: 1.310, b: 3.296 Cost: 0.071409
Epoch  900/3000 W: 1.150, b: 3.658 Cost: 0.016850
Epoch 1200/3000 W: 1.073, b: 3.834 Cost: 0.003976
Epoch 1500/3000 W: 1.035, b: 3.919 Cost: 0.000938
Epoch 1800/3000 W: 1.017, b: 3.961 Cost: 0.000221
Epoch 2100/3000 W: 1.008, b: 3.981 Cost: 0.000052
Epoch 2400/3000 W: 1.004, b: 3.991 Cost: 0.000012
Epoch 2700/3000 W: 1.002, b: 3.996 Cost: 0.000003
Epoch 3000/3000 W: 1.001, b: 3.998 Cost: 0.000001


## Example: Linear Regression using nn.Module 

In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[5], [6], [7]])

model = nn.Linear(1, 1)

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

epochs = 3000
for epoch in range(epochs):
    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    W, b = list(model.parameters())[0], list(model.parameters())[1]
    if (epoch + 1) % 300 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format((epoch + 1), epochs, W.item(), b.item(),
                                                                        cost.item()))



Epoch  300/3000 W: 1.757, b: 2.279 Cost: 0.426866
Epoch  600/3000 W: 1.368, b: 3.164 Cost: 0.100723
Epoch  900/3000 W: 1.179, b: 3.594 Cost: 0.023767
Epoch 1200/3000 W: 1.087, b: 3.803 Cost: 0.005608
Epoch 1500/3000 W: 1.042, b: 3.904 Cost: 0.001323
Epoch 1800/3000 W: 1.020, b: 3.953 Cost: 0.000312
Epoch 2100/3000 W: 1.010, b: 3.977 Cost: 0.000074
Epoch 2400/3000 W: 1.005, b: 3.989 Cost: 0.000017
Epoch 2700/3000 W: 1.002, b: 3.995 Cost: 0.000004
Epoch 3000/3000 W: 1.001, b: 3.997 Cost: 0.000001


## Multivariable Regression  

In [15]:
import torch
import torch.optim as optim

torch.manual_seed(1)

x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.SGD([W, b], lr=1e-5)

epochs = 10000
for epoch in range(1, epochs+1):
    hypothesis = x_train.matmul(W) + b

    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
                epoch, epochs, hypothesis.squeeze().detach(), cost.item()
        ))

Epoch 1000/10000 hypothesis: tensor([153.8956, 184.8843, 176.6528, 198.1000, 141.2950]) Cost: 3.943436
Epoch 2000/10000 hypothesis: tensor([153.7206, 184.7365, 177.3506, 197.6786, 141.4042]) Cost: 2.644381
Epoch 3000/10000 hypothesis: tensor([153.5479, 184.6476, 177.8801, 197.3411, 141.5249]) Cost: 1.807667
Epoch 4000/10000 hypothesis: tensor([153.3857, 184.5969, 178.2857, 197.0694, 141.6458]) Cost: 1.258096
Epoch 5000/10000 hypothesis: tensor([153.2381, 184.5708, 178.5992, 196.8495, 141.7603]) Cost: 0.891718
Epoch 6000/10000 hypothesis: tensor([153.1067, 184.5599, 178.8435, 196.6709, 141.8652]) Cost: 0.644825
Epoch 7000/10000 hypothesis: tensor([152.9914, 184.5584, 179.0355, 196.5252, 141.9589]) Cost: 0.477134
Epoch 8000/10000 hypothesis: tensor([152.8914, 184.5623, 179.1875, 196.4060, 142.0413]) Cost: 0.362609
Epoch 9000/10000 hypothesis: tensor([152.8055, 184.5690, 179.3086, 196.3083, 142.1129]) Cost: 0.284092
Epoch 10000/10000 hypothesis: tensor([152.7322, 184.5770, 179.4057, 196.2

## Multivariable Regression using nn.Module 

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])

y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

model = nn.Linear(3,1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

epochs = 10000
for epoch in range(1, epochs+1):
    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)  

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
                epoch, epochs, prediction.squeeze().detach(), cost.item()
        ))


Epoch 1000/10000 hypothesis: tensor([152.4285, 185.6196, 176.9856, 197.2296, 142.7419]) Cost: 2.343208
Epoch 2000/10000 hypothesis: tensor([152.5653, 185.2724, 177.7319, 196.9231, 142.5502]) Cost: 1.338537
Epoch 3000/10000 hypothesis: tensor([152.6337, 185.0404, 178.2679, 196.6897, 142.4409]) Cost: 0.814669
Epoch 4000/10000 hypothesis: tensor([152.6595, 184.8864, 178.6557, 196.5104, 142.3842]) Cost: 0.532613
Epoch 5000/10000 hypothesis: tensor([152.6597, 184.7850, 178.9385, 196.3714, 142.3606]) Cost: 0.375238
Epoch 6000/10000 hypothesis: tensor([152.6453, 184.7189, 179.1465, 196.2627, 142.3571]) Cost: 0.284090
Epoch 7000/10000 hypothesis: tensor([152.6233, 184.6765, 179.3008, 196.1772, 142.3652]) Cost: 0.229360
Epoch 8000/10000 hypothesis: tensor([152.5981, 184.6498, 179.4163, 196.1092, 142.3794]) Cost: 0.195405
Epoch 9000/10000 hypothesis: tensor([152.5725, 184.6335, 179.5036, 196.0550, 142.3964]) Cost: 0.173734
Epoch 10000/10000 hypothesis: tensor([152.5479, 184.6239, 179.5702, 196.0