<a href="https://colab.research.google.com/github/kimsooyoung/iap_hanyang/blob/main/tutorial01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3/29 수업

In [ ]:
!lsb_release -a 

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic


In [ ]:
import torch
import numpy as np
import logging 

logging.basicConfig(
    format='%(asctime)s %(message)s',
    level=logging.INFO,
    datefmt='%Y-%m-%d %H:%M:%S'
)

In [ ]:
data = np.array([1,2,3], dtype=np.int32)
# data = np.array([1,2,3,4], dtype=np.int32)

In [ ]:
t1 = torch.Tensor(data) # 기본적으로 torch.float32으로 초기화함, 나머지는 동일
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [ ]:
logging.info(t1)
logging.info(t2)
logging.info(t3)
logging.info(t4)

2022-03-29 07:33:47 tensor([1., 2., 3.])
2022-03-29 07:33:47 tensor([1, 2, 3], dtype=torch.int32)
2022-03-29 07:33:47 tensor([1, 2, 3], dtype=torch.int32)
2022-03-29 07:33:47 tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [ ]:
torch.get_default_dtype()

torch.float32

In [ ]:
t2 = torch.tensor(data, dtype=torch.float64)
print(t2, t2.dtype)

tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [ ]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [ ]:
t1 = torch.Tensor(data) # 이건 포멧을 바꾼다 
t2 = torch.tensor(data) # 이게 최고
t3 = torch.as_tensor(data) # 이 두개는 mutable 하다.
t4 = torch.from_numpy(data)

In [ ]:
data[:] = 0
data

array([0, 0, 0])

In [ ]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [ ]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


In [ ]:
data = torch.tensor([[1,2,3],[4,5,6]])
data.shape

torch.Size([2, 3])

In [ ]:
data[:,0]

tensor([1, 4])

## 차원 갖고 놀기

In [ ]:
t = torch.arange(6)
t

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
t_reshape = t.reshape(2,3) # t.view(2,3), t.view(2, -1)과 동일하다.
t_reshape
t.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x = torch.ones(5,1,4,1)
y = torch.ones(3,1,1)

# GPU, CPU 사용하기

In [ ]:
t_cpu = torch.tensor(data=[1,2,3], device='cpu')
t_cpu.device

device(type='cpu')

In [ ]:
t_cuda = torch.tensor(data=[1,2,3], device='cuda:0')
t_cuda.device

device(type='cuda', index=0)

In [ ]:
# t_cuda는 어떤 연산을 해도 gpu에 저장된다.
x = t_cuda + 1
x.device

device(type='cuda', index=0)

In [ ]:
t_cuda_to_cpu = t_cuda.to('cpu')
t_cpu + t_cuda_to_cpu

tensor([2, 4, 6])

In [ ]:
t_test = torch.tensor([1,2,3], dtype=torch.float64)
t_test

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
t_test += 0.00000000001
t_test

tensor([1.0000, 2.0000, 3.0000], dtype=torch.float64)

### 서로 다른 데이터 타입의 tensor끼리 연산하기

In [ ]:
t_int = torch.tensor([1,2,3], dtype=torch.int32)
t_float = torch.tensor([1,2,3], dtype=torch.float32)

print(t_int.dtype, t_float.dtype)
t_int + t_float

torch.int32 torch.float32


tensor([2., 4., 6.])

# requires_grad와 detach

In [58]:
x_grad = torch.tensor(2.5, requires_grad=True)
print(x_grad)

y = x_grad
print(y)

# requires_grad가 False가 된다.
z = x_grad.detach()
print(z, z.requires_grad)

# 다시 True
z.required_grad = True
print(z, z.required_grad)

tensor(2.5000, requires_grad=True)
tensor(2.5000, requires_grad=True)
tensor(2.5000) False
tensor(2.5000) True


### Tensor로부터 파이썬 변수 뽑아내기

In [59]:
tensor_var = torch.tensor(2.5, requires_grad=True)
python_var = tensor_var.item()
python_var

print(type(tensor_var), type(python_var))

<class 'torch.Tensor'> <class 'float'>
